teleop:
  bhand:
    type: topic
    message_type: gripper_ros_common/VelocitySetpoint
    topic_name: bhand_vel
    deadman_buttons: [8]
    axis_mappings:
      -
        axis: 0
        target: spread
        scale: 2.0
      -
        axis: 1
        target: grasp
        scale: 2.0
    
